// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using glamping_addventure3.Models;

#nullable disable

namespace glamping_addventure3.Migrations
{
    [DbContext(typeof(GlampingAddventure3Context))]
    [Migration("20241202181213_o")]
    partial class o
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("glamping_addventure3.Models.Abono", b =>
                {
                    b.Property<int>("Idabono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDAbono");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idabono"));

                    b.Property<double?>("CantAbono")
                        .HasColumnType("float");

                    b.Property<byte[]>("Comprobante")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("FechaAbono")
                        .HasColumnType("date");

                    b.Property<int?>("Idreserva")
                        .HasColumnType("int")
                        .HasColumnName("IDReserva");

                    b.Property<double?>("Pendiente")
                        .HasColumnType("float");

                    b.Property<double?>("Porcentaje")
                        .HasColumnType("float");

                    b.Property<double?>("ValorDeuda")
                        .HasColumnType("float");

                    b.HasKey("Idabono")
                        .HasName("PK__Abono__8647F8A95A40B07E");

                    b.HasIndex("Idreserva");

                    b.ToTable("Abono", (string)null);
                });

            modelBuilder.Entity("glamping_addventure3.Models.Cliente", b =>
                {
                    b.Property<string>("NroDocumento")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Apellido")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<int?>("Idrol")
                        .HasColumnType("int")
                        .HasColumnName("IDRol");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("NroDocumento")
                        .HasName("PK__Clientes__CC62C91C118FB83F");

                    b.HasIndex("Idrol");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("glamping_addventure3.Models.DetalleReservaPaquete", b =>
                {
                    b.Property<int>("IddetalleReservaPaquetes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDDetalleReservaPaquetes");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IddetalleReservaPaquetes"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<int?>("Idpaquete")
                        .HasColumnType("int")
                        .HasColumnName("IDPaquete");

                    b.Property<int?>("Idreserva")
                        .HasColumnType("int")
                        .HasColumnName("IDReserva");

                    b.Property<double?>("Precio")
                        .HasColumnType("float");

                    b.HasKey("IddetalleReservaPaquetes")
                        .HasName("PK__DetalleR__64F9FDAECC7F82D0");

                    b.HasIndex("Idpaquete");

                    b.HasIndex("Idreserva");

                    b.ToTable("DetalleReservaPaquetes");
                });

            modelBuilder.Entity("glamping_addventure3.Models.DetalleReservaServicio", b =>
                {
                    b.Property<int>("IddetalleReservaServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDDetalleReservaServicio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IddetalleReservaServicio"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<int?>("Idreserva")
                        .HasColumnType("int")
                        .HasColumnName("IDReserva");

                    b.Property<int?>("Idservicio")
                        .HasColumnType("int")
                        .HasColumnName("IDServicio");

                    b.Property<double?>("Precio")
                        .HasColumnType("float");

                    b.HasKey("IddetalleReservaServicio")
                        .HasName("PK__DetalleR__B52B22F852F3BE00");

                    b.HasIndex("Idreserva");

                    b.HasIndex("Idservicio");

                    b.ToTable("DetalleReservaServicio", (string)null);
                });

            modelBuilder.Entity("glamping_addventure3.Models.EstadosReserva", b =>
                {
                    b.Property<int>("IdEstadoReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoReserva"));

                    b.Property<string>("NombreEstadoReserva")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("IdEstadoReserva")
                        .HasName("PK__EstadosR__3E654CA898335B91");

                    b.ToTable("EstadosReserva", (string)null);
                });

            modelBuilder.Entity("glamping_addventure3.Models.Habitacion", b =>
                {
                    b.Property<int>("Idhabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDHabitacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idhabitacion"));

                    b.Property<double>("Costo")
                        .HasColumnType("float");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("IdtipodeHabitacion")
                        .HasColumnType("int")
                        .HasColumnName("IDTipodeHabitacion");

                    b.Property<byte[]>("ImagenHabitacion")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("NombreHabitacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Idhabitacion")
                        .HasName("PK__Habitaci__6B4757DADE5D4D9D");

                    b.HasIndex("IdtipodeHabitacion");

                    b.ToTable("Habitacion", (string)null);
                });

            modelBuilder.Entity("glamping_addventure3.Models.HabitacionMueble", b =>
                {
                    b.Property<int>("IdhabitacionMuebles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDHabitacionMuebles");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdhabitacionMuebles"));

                    b.Property<int>("CantidadUsada")
                        .HasColumnType("int");

                    b.Property<int?>("Idhabitacion")
                        .HasColumnType("int")
                        .HasColumnName("IDHabitacion");

                    b.Property<int?>("Idmueble")
                        .HasColumnType("int")
                        .HasColumnName("IDMueble");

                    b.HasKey("IdhabitacionMuebles")
                        .HasName("PK__Habitaci__65CFCA9AC9573D6A");

                    b.HasIndex("Idhabitacion");

                    b.HasIndex("Idmueble");

                    b.ToTable("HabitacionMuebles");
                });

            modelBuilder.Entity("glamping_addventure3.Models.MetodoPago", b =>
                {
                    b.Property<int>("IdMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMetodoPago"));

                    b.Property<string>("NomMetodoPago")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdMetodoPago")
                        .HasName("PK__MetodoPa__6F49A9BED37B368A");

                    b.ToTable("MetodoPago", (string)null);
                });

            modelBuilder.Entity("glamping_addventure3.Models.Mueble", b =>
                {
                    b.Property<int>("Idmueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDMueble");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idmueble"));

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ImagenMueble")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("NombreMueble")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Idmueble")
                        .HasName("PK__Muebles__EAC9F7C88D2DF473");

                    b.ToTable("Muebles");
                });

            modelBuilder.Entity("glamping_addventure3.Models.Paquete", b =>
                {
                    b.Property<int>("Idpaquete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPaquete");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idpaquete"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("Idhabitacion")
                        .HasColumnType("int")
                        .HasColumnName("IDHabitacion");

                    b.Property<int>("Idservicio")
                        .HasColumnType("int")
                        .HasColumnName("IDServicio");

                    b.Property<byte[]>("ImagenPaquete")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("NombrePaquete")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<double?>("Precio")
                        .HasColumnType("float");

                    b.HasKey("Idpaquete")
                        .HasName("PK__Paquetes__4C29513BEC7B59E1");

                    b.HasIndex("Idhabitacion");

                    b.HasIndex("Idservicio");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("glamping_addventure3.Models.Permiso", b =>
                {
                    b.Property<int>("Idpermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPermiso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idpermiso"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EstadoPermisos")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NombrePermisos")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Idpermiso")
                        .HasName("PK__Permisos__F11D75F39691961E");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("glamping_addventure3.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<double?>("Descuento")
                        .HasColumnType("float");

                    b.Property<DateOnly?>("FechaFinalizacion")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaReserva")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdEstadoReserva")
                        .HasColumnType("int");

                    b.Property<double?>("Iva")
                        .HasColumnType("float")
                        .HasColumnName("IVA");

                    b.Property<int?>("MetodoPago")
                        .HasColumnType("int");

                    b.Property<double?>("MontoTotal")
                        .HasColumnType("float");

                    b.Property<string>("NroDocumentoCliente")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<double?>("SubTotal")
                        .HasColumnType("float");

                    b.Property<int?>("UsuarioIdusuario")
                        .HasColumnType("int");

                    b.HasKey("IdReserva")
                        .HasName("PK__Reserva__0E49C69D32CE0362");

                    b.HasIndex("IdEstadoReserva");

                    b.HasIndex("MetodoPago");

                    b.HasIndex("NroDocumentoCliente");

                    b.HasIndex("UsuarioIdusuario");

                    b.ToTable("Reserva", (string)null);
                });

            modelBuilder.Entity("glamping_addventure3.Models.Role", b =>
                {
                    b.Property<int>("Idrol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDRol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idrol"));

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Idrol")
                        .HasName("PK__Roles__A681ACB61E786D48");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("glamping_addventure3.Models.RolesPermiso", b =>
                {
                    b.Property<int>("IdrolPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDRolPermiso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdrolPermiso"));

                    b.Property<int?>("Idpermiso")
                        .HasColumnType("int")
                        .HasColumnName("IDPermiso");

                    b.Property<int?>("Idrol")
                        .HasColumnType("int")
                        .HasColumnName("IDRol");

                    b.HasKey("IdrolPermiso")
                        .HasName("PK__RolesPer__3F09FABFE79F4DA2");

                    b.HasIndex("Idpermiso");

                    b.HasIndex("Idrol");

                    b.ToTable("RolesPermisos");
                });

            modelBuilder.Entity("glamping_addventure3.Models.Servicio", b =>
                {
                    b.Property<int>("Idservicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDServicio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idservicio"));

                    b.Property<int>("CantidadMaximaPersonas")
                        .HasColumnType("int");

                    b.Property<double>("Costo")
                        .HasColumnType("float");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Duracion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Idservicio")
                        .HasName("PK__Servicio__3CCE7416F3CB208A");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("glamping_addventure3.Models.TipodeHabitacion", b =>
                {
                    b.Property<int>("IdtipodeHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTipodeHabitacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdtipodeHabitacion"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreTipodeHabitacion")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("IdtipodeHabitacion")
                        .HasName("PK__TipodeHa__9BD4086C17A3DCE5");

                    b.ToTable("TipodeHabitacion", (string)null);
                });

            modelBuilder.Entity("glamping_addventure3.Models.TokenRecuperacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Usado")
                        .HasColumnType("bit");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TokenRec__3214EC07DFC4F73E");

                    b.ToTable("TokenRecuperacion", (string)null);
                });

            modelBuilder.Entity("glamping_addventure3.Models.Usuario", b =>
                {
                    b.Property<int>("Idusuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDUsuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idusuario"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Contrasena")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Idrol")
                        .HasColumnType("int")
                        .HasColumnName("IDRol");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("NumeroDocumento")
                        .HasColumnType("int");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Idusuario")
                        .HasName("PK__Usuarios__52311169B5B0B2C3");

                    b.HasIndex("Idrol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("glamping_addventure3.Models.Abono", b =>
                {
                    b.HasOne("glamping_addventure3.Models.Reserva", "IdreservaNavigation")
                        .WithMany("Abonos")
                        .HasForeignKey("Idreserva")
                        .HasConstraintName("FK_Abono_Reserva");

                    b.Navigation("IdreservaNavigation");
                });

            modelBuilder.Entity("glamping_addventure3.Models.Cliente", b =>
                {
                    b.HasOne("glamping_addventure3.Models.Role", "IdrolNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("Idrol")
                        .HasConstraintName("FK_Clientes_Roles");

                    b.Navigation("IdrolNavigation");
                });

            modelBuilder.Entity("glamping_addventure3.Models.DetalleReservaPaquete", b =>
                {
                    b.HasOne("glamping_addventure3.Models.Paquete", "IdpaqueteNavigation")
                        .WithMany("DetalleReservaPaquetes")
                        .HasForeignKey("Idpaquete")
                        .HasConstraintName("FK_DetalleReservaPaquetes_Paquete");

                    b.HasOne("glamping_addventure3.Models.Reserva", "IdreservaNavigation")
                        .WithMany("DetalleReservaPaquetes")
                        .HasForeignKey("Idreserva")
                        .HasConstraintName("FK_DetalleReservaPaquetes_Reserva");

                    b.Navigation("IdpaqueteNavigation");

                    b.Navigation("IdreservaNavigation");
                });

            modelBuilder.Entity("glamping_addventure3.Models.DetalleReservaServicio", b =>
                {
                    b.HasOne("glamping_addventure3.Models.Reserva", "IdreservaNavigation")
                        .WithMany("DetalleReservaServicios")
                        .HasForeignKey("Idreserva")
                        .HasConstraintName("FK_DetalleReservaServicio_Reserva");

                    b.HasOne("glamping_addventure3.Models.Servicio", "IdservicioNavigation")
                        .WithMany("DetalleReservaServicios")
                        .HasForeignKey("Idservicio")
                        .HasConstraintName("FK_DetalleReservaServicio_Servicio");

                    b.Navigation("IdreservaNavigation");

                    b.Navigation("IdservicioNavigation");
                });

            modelBuilder.Entity("glamping_addventure3.Models.Habitacion", b =>
                {
                    b.HasOne("glamping_addventure3.Models.TipodeHabitacion", "IdtipodeHabitacionNavigation")
                        .WithMany("Habitacions")
                        .HasForeignKey("IdtipodeHabitacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Habitacion_TipodeHabitacion");

                    b.Navigation("IdtipodeHabitacionNavigation");
                });

            modelBuilder.Entity("glamping_addventure3.Models.HabitacionMueble", b =>
                {
                    b.HasOne("glamping_addventure3.Models.Habitacion", "IdhabitacionNavigation")
                        .WithMany("HabitacionMuebles")
                        .HasForeignKey("Idhabitacion")
                        .HasConstraintName("FK_HabitacionMuebles_Habitacion");

                    b.HasOne("glamping_addventure3.Models.Mueble", "IdmuebleNavigation")
                        .WithMany("HabitacionMuebles")
                        .HasForeignKey("Idmueble")
                        .HasConstraintName("FK_HabitacionMuebles_Muebles");

                    b.Navigation("IdhabitacionNavigation");

                    b.Navigation("IdmuebleNavigation");
                });

            modelBuilder.Entity("glamping_addventure3.Models.Paquete", b =>
                {
                    b.HasOne("glamping_addventure3.Models.Habitacion", "IdhabitacionNavigation")
                        .WithMany("Paquetes")
                        .HasForeignKey("Idhabitacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Habitacione_Paquetes");

                    b.HasOne("glamping_addventure3.Models.Servicio", "IdservicioNavigation")
                        .WithMany("Paquetes")
                        .HasForeignKey("Idservicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Servicio_Paquetes");

                    b.Navigation("IdhabitacionNavigation");

                    b.Navigation("IdservicioNavigation");
                });

            modelBuilder.Entity("glamping_addventure3.Models.Reserva", b =>
                {
                    b.HasOne("glamping_addventure3.Models.EstadosReserva", "IdEstadoReservaNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdEstadoReserva")
                        .HasConstraintName("FK__Reserva__IdEstad__6C190EBB");

                    b.HasOne("glamping_addventure3.Models.MetodoPago", "MetodoPagoNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("MetodoPago")
                        .HasConstraintName("FK__Reserva__MetodoP__6D0D32F4");

                    b.HasOne("glamping_addventure3.Models.Cliente", "NroDocumentoClienteNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("NroDocumentoCliente")
                        .HasConstraintName("FK__Reserva__NroDocu__6B24EA82");

                    b.HasOne("glamping_addventure3.Models.Usuario", null)
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioIdusuario");

                    b.Navigation("IdEstadoReservaNavigation");

                    b.Navigation("MetodoPagoNavigation");

                    b.Navigation("NroDocumentoClienteNavigation");
                });

            modelBuilder.Entity("glamping_addventure3.Models.RolesPermiso", b =>
                {
                    b.HasOne("glamping_addventure3.Models.Permiso", "IdpermisoNavigation")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("Idpermiso")
                        .HasConstraintName("FK__RolesPerm__IDPer__534D60F1");

                    b.HasOne("glamping_addventure3.Models.Role", "IdrolNavigation")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("Idrol")
                        .HasConstraintName("FK__RolesPerm__IDRol__52593CB8");

                    b.Navigation("IdpermisoNavigation");

                    b.Navigation("IdrolNavigation");
                });

            modelBuilder.Entity("glamping_addventure3.Models.Usuario", b =>
                {
                    b.HasOne("glamping_addventure3.Models.Role", "IdrolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("Idrol")
                        .HasConstraintName("FK__Usuarios__IDRol__5629CD9C");

                    b.Navigation("IdrolNavigation");
                });

            modelBuilder.Entity("glamping_addventure3.Models.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("glamping_addventure3.Models.EstadosReserva", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("glamping_addventure3.Models.Habitacion", b =>
                {
                    b.Navigation("HabitacionMuebles");

                    b.Navigation("Paquetes");
                });

            modelBuilder.Entity("glamping_addventure3.Models.MetodoPago", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("glamping_addventure3.Models.Mueble", b =>
                {
                    b.Navigation("HabitacionMuebles");
                });

            modelBuilder.Entity("glamping_addventure3.Models.Paquete", b =>
                {
                    b.Navigation("DetalleReservaPaquetes");
                });

            modelBuilder.Entity("glamping_addventure3.Models.Permiso", b =>
                {
                    b.Navigation("RolesPermisos");
                });

            modelBuilder.Entity("glamping_addventure3.Models.Reserva", b =>
                {
                    b.Navigation("Abonos");

                    b.Navigation("DetalleReservaPaquetes");

                    b.Navigation("DetalleReservaServicios");
                });

            modelBuilder.Entity("glamping_addventure3.Models.Role", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("RolesPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("glamping_addventure3.Models.Servicio", b =>
                {
                    b.Navigation("DetalleReservaServicios");

                    b.Navigation("Paquetes");
                });

            modelBuilder.Entity("glamping_addventure3.Models.TipodeHabitacion", b =>
                {
                    b.Navigation("Habitacions");
                });

            modelBuilder.Entity("glamping_addventure3.Models.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
